In [1]:
code = dict()

In [2]:
code['A'] =  """
ADM1
first-order administrative division
a primary administrative division of a country, such as a state in the United States
ADM1H
historical first-order administrative division
a former first-order administrative division
ADM2
second-order administrative division
a subdivision of a first-order administrative division
ADM2H
historical second-order administrative division
a former second-order administrative division
ADM3
third-order administrative division
a subdivision of a second-order administrative division
ADM3H
historical third-order administrative division
a former third-order administrative division
ADM4
fourth-order administrative division
a subdivision of a third-order administrative division
ADM4H
historical fourth-order administrative division
a former fourth-order administrative division
ADM5
fifth-order administrative division
a subdivision of a fourth-order administrative division
ADM5H
historical fifth-order administrative division
a former fifth-order administrative division
PCL
political entity

PCLI
independent political entity""".split()

In [3]:
code["H"] = """
BAY
bay
a coastal indentation between two capes or headlands, larger than a cove but smaller than a gulf
BAYS
bays
coastal indentations between two capes or headlands, larger than a cove but smaller than a gulf
FJD
fjord
a long, narrow, steep-walled, deep-water arm of the sea at high latitudes, usually along mountainous coasts
FJDS
fjords
long, narrow, steep-walled, deep-water arms of the sea at high latitudes, usually along mountainous coasts
FLLS
waterfall(s)
a perpendicular or very steep descent of the water of a stream
GLCR
glacier(s)
a mass of ice, usually at high latitudes or high elevations, with sufficient thickness to flow away from the source area in lobes, tongues, or masses
GULF
gulf
a large recess in the coastline, larger than a bay
LK
lake
a large inland body of standing water
LKS
lakes
large inland bodies of standing water
OCN
ocean
one of the major divisions of the vast expanse of salt water covering part of the earth
SEA
sea
a large body of salt water more or less confined by continuous land or chains of islands forming a subdivision of an ocean
STRT
strait
a relatively narrow waterway, usually narrower and less extensive than a sound, connecting two larger bodies of water
COVE
cove(s)
a small coastal indentation, smaller than a bay


STM
stream
a body of running water moving to a lower level in a channel on land
STMS
streams
bodies of running water moving to a lower level in a channel on land""".split()

In [4]:
code['L'] ="""AREA
area
a tract of land without homogeneous character or boundaries
LAND
arctic land
a tract of land in the Arctic
PRK
park
an area, often of forested land, maintained as a place of beauty, or for recreation
TRB
tribal area
a tract of land used by nomadic or other tribes
RGN
region
an area distinguished by one or more observable physical or cultural characteristics""".split()

In [5]:
code["P"] = """
Denne Gruppen er viktig å hierarkisere. PPL må være nederst i hierarkiet. Dersom en token passer med både PPLC og PPL, må PPLC velges. Samme med alle varianter av PPLA.

If PPL så må token == name
PPL
populated place
a city, town, village, or other agglomeration of buildings where people live and work
PPLA
seat of a first-order administrative division
seat of a first-order administrative division (PPLC takes precedence over PPLA)
PPLA2
seat of a second-order administrative division


PPLA3
seat of a third-order administrative division


PPLA4
seat of a fourth-order administrative division


PPLA5
seat of a fifth-order administrative division


PPLC
capital of a political entity


PPLCH
historical capital of a political entity
a former capital of a political entity""".split()

In [6]:
code["T"]="""
CAPE
cape
a land area, more prominent than a point, projecting into the sea and marking a notable change in coastal direction
DLTA
delta
a flat plain formed by alluvial deposits at the mouth of a stream
DSRT
desert
a large area with little or no vegetation due to extreme environmental conditions
ISL
island
a tract of land, smaller than a continent, surrounded by water at high water
ISLS
islands
tracts of land, smaller than a continent, surrounded by water at high water
PEN
peninsula
an elongate area of land projecting into a body of water and nearly surrounded by water
VAL
valley
an elongated depression usually traversed by a stream



MT
mountain
an elevation standing high above the surrounding area with small summit area, steep slopes and local relief of 300m or more
MTS
mountains
a mountain range or a group of mountains or high ridges
""".split()

In [7]:
codes = {k:[x for x in code[k] if x.upper() == x and x.isalnum()] for k in code}

In [8]:
codes

{'A': ['ADM1',
  'ADM1H',
  'ADM2',
  'ADM2H',
  'ADM3',
  'ADM3H',
  'ADM4',
  'ADM4H',
  'ADM5',
  'ADM5H',
  'PCL',
  'PCLI'],
 'H': ['BAY',
  'BAYS',
  'FJD',
  'FJDS',
  'FLLS',
  'GLCR',
  'GULF',
  'LK',
  'LKS',
  'OCN',
  'SEA',
  'STRT',
  'COVE',
  'STM',
  'STMS'],
 'L': ['AREA', 'LAND', 'PRK', 'TRB', 'RGN'],
 'P': ['PPL',
  'PPLC',
  'PPLC',
  'PPL',
  'PPL',
  'PPLA',
  'PPLA2',
  'PPLA3',
  'PPLA4',
  'PPLA5',
  'PPLC',
  'PPLCH'],
 'T': ['CAPE', 'DLTA', 'DSRT', 'ISL', 'ISLS', 'PEN', 'VAL', 'MT', 'MTS']}

In [11]:
import dhlab as dh
import dhlab.api.dhlab_api as api
import pandas as pd

In [38]:
d = dh.GeoNames(["Ålesund", "Trondhjem", "Eidsvold","Eidsvoll", "Christiania", "Throndhjem", "Bjørgvin", "Drammen", "Sunndalsøra", "Kristiansund", "Lofoten"])

In [31]:
features = pd.DataFrame([(k,y) for k in codes for y in codes[k]], columns=['feature_class', 'feature_code'])

In [32]:
features

   feature_class feature_code
0              A         ADM1
1              A        ADM1H
2              A         ADM2
3              A        ADM2H
4              A         ADM3
5              A        ADM3H
6              A         ADM4
7              A        ADM4H
8              A         ADM5
9              A        ADM5H
10             A          PCL
11             A         PCLI
12             H          BAY
13             H         BAYS
14             H          FJD
15             H         FJDS
16             H         FLLS
17             H         GLCR
18             H         GULF
19             H           LK
20             H          LKS
21             H          OCN
22             H          SEA
23             H         STRT
24             H         COVE
25             H          STM
26             H         STMS
27             L         AREA
28             L         LAND
29             L          PRK
30             L          TRB
31             L          RGN
32             P          PPL
33             P         PPLC
34             P         PPLC
35             P          PPL
36             P          PPL
37             P         PPLA
38             P        PPLA2
39             P        PPLA3
40             P        PPLA4
41             P        PPLA5
42             P         PPLC
43             P        PPLCH
44             T         CAPE
45             T         DLTA
46             T         DSRT
47             T          ISL
48             T         ISLS
49             T          PEN
50             T          VAL
51             T           MT
52             T          MTS

In [39]:
d.places.merge(features, left_on=['feature_class', 'feature_code'], right_on=['feature_class', 'feature_code']).drop_duplicates()

,geonameid,name,alternatename,latitude,longitude,feature_class,feature_code
0,3143244,Oslo,Christiania,59.91273,10.74609,P,PPLC
3,3159016,Drammen,Drammen,59.74389,10.20449,P,PPLA
4,6453372,Drammen,Drammen,59.74536,10.20597,A,ADM2
5,2167693,Eidsvold,Eidsvold,-25.37168,151.12145,P,PPL
8,3158608,Eidsvoll,Eidsvold,60.33110,11.26264,P,PPLA2
9,3158608,Eidsvoll,Eidsvoll,60.33110,11.26264,P,PPLA2
10,3149312,Kristiansund,Kristiansund,63.11045,7.72795,P,PPLA2
11,3147088,Lofoten,Lofoten,68.20483,12.79496,T,ISLS
12,3135377,Sunndalsøra,Sunndalsøra,62.67519,8.56327,P,PPLA2
13,3133880,Trondheim,Trondhjem,63.43049,10.39506,P,PPLA2
14,3163392,Ålesund,Ålesund,62.47225,6.15492,P,PPLA2

In [40]:
d.places

,geonameid,name,alternatename,latitude,longitude,feature_class,feature_code
0,2623186,Christiania,Christiania,55.67346,12.59765,P,PPLX
1,3143244,Oslo,Christiania,59.91273,10.74609,P,PPLC
2,3159016,Drammen,Drammen,59.74389,10.20449,P,PPLA
3,6453372,Drammen,Drammen,59.74536,10.20597,A,ADM2
4,9591881,Drammen,Drammen,57.99584,7.48850,H,INLT
5,2167693,Eidsvold,Eidsvold,-25.37168,151.12145,P,PPL
6,3158608,Eidsvoll,Eidsvold,60.33110,11.26264,P,PPLA2
7,3158609,Eidsvoll,Eidsvold,68.98999,19.60383,S,FRM
8,8799757,Eidsvold,Eidsvold,-25.37749,151.08166,S,HMSD
9,8826999,Eidsvold Station,Eidsvold,-25.36962,151.12724,S,RSTN
10,3158608,Eidsvoll,Eidsvoll,60.33110,11.26264,P,PPLA2
11,3158609,Eidsvoll,Eidsvoll,68.98999,19.60383,S,FRM
12,8532067,Eidsvoll,Eidsvoll,60.32341,11.24437,S,CH
13,8558094,Eidsvoll,Eidsvoll,60.32969,11.24769,S,RSTN
14,8586458,Eidsvoll,Eidsvoll,60.32659,11.25203,S,BDG
15,9415982,Eidsvoll,Eidsvoll,60.71908,10.29283,S,FRM
16,9437537,Eidsvoll,Eidsvoll,63.72277,9.82982,S,FRM
17,9439299,Eidsvoll,Eidsvoll,62.59055,7.48196,S,FRM
18,9451159,Eidsvoll,Eidsvoll,63.23457,9.03523,S,FRM
19,9456009,Eidsvoll,Eidsvoll,62.92695,7.22312,S,FRM
20,9480997,Eidsvoll,Eidsvoll,68.73785,14.58371,S,FRM
21,3149312,Kristiansund,Kristiansund,63.11045,7.72795,P,PPLA2
22,3147088,Lofoten,Lofoten,68.20483,12.79496,T,ISLS
23,3135377,Sunndalsøra,Sunndalsøra,62.67519,8.56327,P,PPLA2
24,3133880,Trondheim,Trondhjem,63.43049,10.39506,P,PPLA2
25,9478046,Trondhjem,Trondhjem,60.70993,11.32799,S,FRM
26,3163391,Ålesundet,Ålesund,61.46667,5.46667,H,CHNM
27,3163392,Ålesund,Ålesund,62.47225,6.15492,P,PPLA2